# Generated by Django 5.0.1 on 2024-02-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadharcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar',
            name='img',
        ),
        migrations.AddField(
            model_name='aadhar',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
